import type { IntersectionResult } from '@/types/intersection'
import type { GeneratorConfig, GeneratedArtifacts } from '@/types/generator'
import type { StructureDefinition, ElementDefinition } from '@/types/fhir'
import { maxToString } from './intersectionEngine'

const KNOWN_ALIASES: Record<string, string> = {
  'http://snomed.info/sct': '$SCT',
  'http://loinc.org': '$LOINC',
  'http://hl7.org/fhir/sid/icd-10': '$ICD10',
  'http://hl7.org/fhir/sid/icd-10-cm': '$ICD10CM',
  'http://terminology.hl7.org/CodeSystem/v3-ActCode': '$ActCode',
  'http://terminology.hl7.org/CodeSystem/v2-0203': '$v2-0203',
  'http://hl7.org/fhir/ValueSet/': '$fhir-vs',
}

function aliasFor(uri: string): string | null {
  for (const [prefix, alias] of Object.entries(KNOWN_ALIASES)) {
    if (uri.startsWith(prefix)) return alias
  }
  return null
}

export function generateArtifacts(
  result: IntersectionResult,
  config: GeneratorConfig
): GeneratedArtifacts {
  const fsh = generateFSH(result, config)
  const sd = generateStructureDefinition(result, config)

  return {
    profileName: config.profileName,
    profileId: config.profileId,
    baseType: result.baseType,
    fhirVersion: config.fhirVersion,
    fshSource: fsh,
    structureDefinitionJson: JSON.stringify(sd, null, 2),
    generatedAt: Date.now(),
    sourceIGs: result.profileNames,
    elementCount: result.elements.length,
  }
}

function generateFSH(result: IntersectionResult, config: GeneratorConfig): string {
  const lines: string[] = []
  const usedValueSets = new Set<string>()

  // Collect all valuesets for aliases
  for (const el of result.elements) {
    if (el.consensusBinding?.valueSet) {
      usedValueSets.add(el.consensusBinding.valueSet)
    }
  }

  // Generate aliases
  const aliasMap = new Map<string, string>()
  const usedAliasNames = new Set<string>()
  for (const vs of usedValueSets) {
    const alias = aliasFor(vs)
    if (alias && !usedAliasNames.has(alias)) {
      aliasMap.set(vs, alias)
      usedAliasNames.add(alias)
    }
  }

  if (aliasMap.size > 0) {
    for (const [uri, alias] of aliasMap) {
      lines.push(`Alias: ${alias} = ${uri}`)
    }
    lines.push('')
  }

  // Profile header
  lines.push(`Profile: ${config.profileName}`)
  lines.push(`Parent: ${result.baseType}`)
  lines.push(`Id: ${config.profileId}`)
  lines.push(`Title: "${config.profileName}"`)
  lines.push(
    `Description: "Intersection profile generated by CIMBench from ${result.totalProfiles} source IGs: ${result.profileNames.join(', ')}"`
  )
  lines.push('')

  // Metadata caret rules
  lines.push('* ^status = #draft')
  lines.push('* ^experimental = true')
  lines.push(`* ^version = "0.1.0"`)
  if (config.includeComments) {
    lines.push(`// Generated: ${new Date(result.generatedAt).toISOString()}`)
    lines.push(`// Source IGs: ${result.profileNames.join(', ')}`)
    lines.push(`// Threshold: ${Math.round(result.config.threshold * 100)}%`)
  }
  lines.push('')

  // Element rules
  for (const el of result.elements) {
    const path = el.normalizedPath

    if (config.includeComments && el.shortDescription) {
      lines.push(`// ${path}: ${el.shortDescription}`)
    }

    const flags: string[] = []
    if (el.consensusMustSupport) flags.push('MS')

    // Cardinality + MS on one line
    const cardPart = `${el.consensusMin}..${maxToString(el.consensusMax)}`
    const flagPart = flags.length > 0 ? ` ${flags.join(' ')}` : ''

    if (el.cardinalityResolution === 'conflict') {
      if (config.includeConflictNotes) {
        lines.push(`// CARDINALITY CONFLICT on ${path}:`)
        for (const [ig, card] of Object.entries(el.cardinalityVariants)) {
          lines.push(`//   ${ig}: ${card}`)
        }
      }
      lines.push(`// * ${path} ${cardPart}${flagPart}  // REVIEW: cardinality conflict`)
    } else {
      lines.push(`* ${path} ${cardPart}${flagPart}`)
    }

    // Type constraint (only if single type and not the default)
    if (!el.typeConflict && el.consensusTypes.length === 1) {
      lines.push(`* ${path} only ${el.consensusTypes[0]}`)
    } else if (el.typeConflict && config.includeConflictNotes) {
      lines.push(`// TYPE CONFLICT on ${path}: ${JSON.stringify(el.typeVariants)}`)
    }

    // Binding
    if (el.consensusBinding) {
      const vs = el.consensusBinding.valueSet ?? ''
      const alias = aliasMap.get(vs)
      const vsRef = alias ? alias : vs ? `${vs}` : ''
      if (vsRef) {
        if (el.consensusBinding.valueSetConflict && config.includeConflictNotes) {
          lines.push(`// BINDING VALUE SET CONFLICT on ${path}:`)
          for (const [ig, v] of Object.entries(el.consensusBinding.valueSetVariants)) {
            lines.push(`//   ${ig}: ${v}`)
          }
        }
        lines.push(`* ${path} from ${vsRef} (${el.consensusBinding.strength})`)
      }
    }
  }

  // Conflict summary at end
  if (result.conflicts.length > 0 && config.includeConflictNotes) {
    lines.push('')
    lines.push('// ═══════════════════════════════════')
    lines.push('// ELEMENTS REQUIRING MANUAL REVIEW')
    lines.push('// ═══════════════════════════════════')
    for (const el of result.conflicts) {
      if (el.cardinalityResolution === 'conflict') {
        lines.push(`// ${el.normalizedPath} — cardinality conflict: ${JSON.stringify(el.cardinalityVariants)}`)
      }
      if (el.typeConflict) {
        lines.push(`// ${el.normalizedPath} — type conflict: ${JSON.stringify(el.typeVariants)}`)
      }
    }
  }

  return lines.join('\n')
}

function generateStructureDefinition(
  result: IntersectionResult,
  config: GeneratorConfig
): StructureDefinition {
  const url = `${config.canonical}/StructureDefinition/${config.profileId}`

  const differentialElements: ElementDefinition[] = result.elements
    .filter(el => el.cardinalityResolution !== 'conflict')
    .map(el => {
      const elem: ElementDefinition = {
        id: el.normalizedPath,
        path: el.normalizedPath,
        min: el.consensusMin,
        max: maxToString(el.consensusMax),
      }

      if (el.consensusMustSupport) elem.mustSupport = true

      if (!el.typeConflict && el.consensusTypes.length > 0) {
        elem.type = el.consensusTypes.map(code => ({ code }))
      }

      if (el.consensusBinding?.valueSet && !el.consensusBinding.valueSetConflict) {
        elem.binding = {
          strength: el.consensusBinding.strength,
          valueSet: el.consensusBinding.valueSet,
        }
      }

      if (el.shortDescription) elem.short = el.shortDescription

      return elem
    })

  const sd: StructureDefinition = {
    resourceType: 'StructureDefinition',
    id: config.profileId,
    url,
    version: '0.1.0',
    name: config.profileName,
    title: config.profileName,
    status: 'draft',
    experimental: true,
    description: `Intersection profile generated by CIMBench from: ${result.profileNames.join(', ')}`,
    fhirVersion: config.fhirVersion,
    kind: 'resource',
    abstract: false,
    type: result.baseType,
    baseDefinition: `http://hl7.org/fhir/StructureDefinition/${result.baseType}`,
    derivation: 'constraint',
    differential: {
      element: differentialElements,
    },
  }

  return sd
}
